version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: always
    environment:
      MYSQL_PASSWORD: /run/secrets/db_root_password
    secrets:
      - db_root_password
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
volumes:
  db_data:

secrets:
  db_root_password:
    file: ./db_root_password  